site_name: JKLab WIKI
site_url: https://jykim.github.io/wiki
theme:
  name: readthedocs
nav:
 - Home: index.md
 - BerEditor: bereditor.md
 - CertMan: certman.md
 - CryptokiMan: cryptokiman.md
 - About: about.md
